### ISSUE TITLE
Code feedback

### ISSUE THREAD

**Issue by ShaughnAnderson94** [fac28/connote#105]
wow who is this cool user??
No seriously feedback

Good: I love the night and day mode they are both beautiful in different ways UI overall is amazing

fun selection of poems

Prompts are unique for each poem thats cool!

I like this gooselover its fun seeing them uncover the joy of poetry just like your future users will

you have well organized code 

Bad: maybe stop people from moving to the next stage without highlighting a word instead of just stopping submiting in the end.
 
highlight being a click and drag would be ideal but thats probably difficult 

not clear what bookmark circle is till after its clicked and sometimes it loaded the symbol in weird

**Comment by sgroi-l** [comment]
Thanks Shaughn, the bookmark UI has been fixed now and other issues are being worked on
